version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - "ok-to-test"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - "ok-to-test"
  ignore:
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-minor"]
